default: 
  image: ubuntu:latest
  before_script:
    - docker info


build-homepage:
  script:
    - docker build -t homepage
    - docker run homepage 
    #- docker tag my-image my-registry:5000/my-image
    #- docker push my-registry:5000/my-image
