default: 
  image: docker:latest
  before_script:
    - docker info

build-homepage:
  script:
    - docker build -t gitlab.dorwinia.com:5050/homelab/docker-homepage .
    - docker push gitlab.dorwinia.com:5050/homelab/docker-homepage
