stages:
  - default
  - build_push

default: 
  image: docker:latest
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_push:
  stage: build_push
  script:
    - docker build -t gitlab.dorwinia.com:5050/homelab/docker-homepage .
    - docker push gitlab.dorwinia.com:5050/homelab/docker-homepage
